---
- hosts: all
  become: true

  vars:
    join_command: "{{ lookup('file', '/tmp/join-command') }}"

  tasks:
    - name: Include task to create hosts file
      ansible.builtin.include_tasks: includes/create_hosts_file.yml

    - name: Include task to install packages that enable apt over HTTPS
      ansible.builtin.include_tasks: includes/apt_over_https.yml

    - name: Include task to install useful packages
      ansible.builtin.include_tasks: includes/install_useful_packages.yml

    - name: Include task to install Docker
      ansible.builtin.include_tasks: includes/install_docker.yml

    - name: Include task to bootstrap k8s
      ansible.builtin.include_tasks: includes/bootstrap_k8s.yml

    - name: Join the node to cluster
      ansible.builtin.command: "{{ join_command }}"

  # Setup a handler for checking Docker daemon
  handlers:
    - name: docker status
      ansible.builtin.service:
        name: docker
        state: started
