---
- hosts: all
  become: true

  vars:
    join_command: "{{ lookup('file', '/tmp/join-command') }}"
    cert_key: "{{ lookup('file', '/tmp/cert-key') }}"

  tasks:
    - name: Include task to create hosts file
      ansible.builtin.include_tasks: includes/create_hosts_file.yml

    - name: Include task to create resolv.conf
      ansible.builtin.include_tasks: includes/create_resolv_conf.yml

    - name: Include task to install packages that enable apt over HTTPS
      ansible.builtin.include_tasks: includes/apt_over_https.yml

    - name: Include task to install useful packages
      ansible.builtin.include_tasks: includes/install_useful_packages.yml

    - name: Include task to install Docker
      ansible.builtin.include_tasks: includes/install_docker.yml

    - name: Include task to bootstrap k8s
      ansible.builtin.include_tasks: includes/bootstrap_k8s.yml

    - name: Join the node to cluster
      ansible.builtin.command: "{{ join_command }} --control-plane --certificate-key {{ cert_key }} --apiserver-advertise-address {{ node_ip }}"

    - name: Include task to setup kubeconfig
      ansible.builtin.include_tasks: includes/setup_kube_config.yml

  # Setup a handler for checking Docker daemon
  handlers:
    - name: docker status
      ansible.builtin.service:
        name: docker
        state: started
